### ISSUE TITLE
Nice work! I am also interested in designing KB with trackball, so I have some questions if you could find time to answer.

### ISSUE THREAD

**Issue by klesh** [protieusz/Sachiel#1]
1. I didn't see any bearing to reduce the traction. How does it feel when rolling the ball? Is it smooth enough? 
2. Are there any cheaper sensors as replacements for PMW3360?

**Comment by protieusz** [comment]
1. Unfortunately I haven't learned how to design those cutouts for rollers. I have tried rollers in other designs and they feel slightly smoother. Without rollers it is useable and not super super smooth. Also depends on the case material PLA is good enough for me. Nylon and resin you will need POM balls. It depends on tolerance of your printer. Sometimes I get really good compatibility with all types of balls but most of the time POM ball always works. 
2. As for pmw sensor sorry there are not cheaper version since pmw is proprietary and the best in the market. There is the 3610 that most ppl use for wireless built but I dunno anything about it other than the name. You will have to research on your own. I am content with wired custom keebs. Good luck.

**Comment by klesh** [comment]
@protieusz Lovely, thanks for the information, it is very helpful.
